### ISSUE TITLE
Allowing cape changing by players is playing with fire

### ISSUE THREAD

**Issue by asiekierka** [killjoy1221/ValhallaSkinServer#3]
Just as a warning - Mojang does not like it when entities who are not them give out capes. They like keeping them to themselves.

(In all honesty, they haven't done anything to anyone handing out capes - OptiFine's empire still stands - but I think it's best to be aware of it.)

**Comment by killjoy1221** [comment]
I don't make it too easy to add your own cape. The server may support uploading it, but not the client. Basically if you want to give yourself a cape, you need to use the api manually. Is not that much of a barrier, but it'll give people a sense of accomplishment if they manage to do it.
